name: Publish TestBase to preview repository

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: aelf.testing.testbase
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.*'  # Change this to the .NET version you're using

      - name: Read version from version.props
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/preview" ]]; then
            version=$(grep -oP '<Version>\K[^<]+' version.props)
            echo "VERSION=$version-preview.${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
          else
            version=$(grep -oP '<Version>\K[^<]+' version.props)
            echo "VERSION=$version" >> $GITHUB_ENV
          fi

      - name: Restore dependencies
        run: dotnet restore **/*.csproj

      - name: Build project
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: dotnet build --configuration Release /p:Version=$VERSION /p:Platform="Any CPU" **/*.csproj

      - name: Pack
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: dotnet pack --configuration Release --output nupkgs /p:Version=$VERSION /p:Platform="Any CPU" **/*.csproj

      - name: Publish NuGet packages
        run: |
          dotnet nuget push '**/*.nupkg' --api-key ${{ secrets.PREVIEW_NUGET_API_KEY }} --source ${{ secrets.PREVIEW_NUGET_FEED_URL }}

